<?php

use Illuminate\Database\Seeder;

class UserTableSeeder extends Seeder {
/**
 * Run the database seeds.
 *
 * @return void
 */
	public function run() {
		DB::table('users')->delete();

		DB::table('users')->insert(array(
  array('id' => '10001','full_name' => 'Tony','user_name' => 'Ion','email' => 'tony@gmail.com','password' => '$2y$10$vgmjv.a2IGgmdITrXUcqK.IHCZMWoDPdjOY2T9J6mwLs9GhrynOsC','remember_token' => 'BqudmpnwGUps5PHDwPtxK06iGt7EsTUL5ngLSUzmHytWAzl7KK5U9IpTdfG2','store_name' => 'Odella Design Studio','already_selling' => NULL,'product_categories' => NULL,'dob' => NULL,'gender' => NULL,'location' => NULL,'bio' => NULL,'website' => NULL,'google_id' => NULL,'twitter_id' => NULL,'facebook_id' => NULL,'device_type' => NULL,'device_id' => NULL,'timezone' => 'UTC','timeformat' => '0','languages' => NULL,'currency_code' => NULL,'status' => 'Active','featured' => 'Yes','is_header' => 'Yes','type' => 'merchant','created_at' => '2017-09-13 20:03:36','updated_at' => '2020-01-31 20:29:45','deleted_at' => NULL),
  array('id' => '10002','full_name' => 'Test','user_name' => 'User','email' => 'test@trioangle.com','password' => '$2y$10$MVQ5HWH8hf8.hmVCbUOOBOOWE7XsMn.8wvZJMPzOcNga6hmNBi2.W','remember_token' => 'sA6LLq6BnWKG4itT317PTjUkAmCosIjwEubkoMuRwMU9h23FfaJzFotyRr5C','store_name' => 'Japan Trend Shop','already_selling' => NULL,'product_categories' => NULL,'dob' => '1985-02-15','gender' => 'Male','location' => 'England','bio' => '','website' => 'https://spiffy.trioangle.com/','google_id' => NULL,'twitter_id' => NULL,'facebook_id' => NULL,'device_type' => NULL,'device_id' => NULL,'timezone' => 'UTC','timeformat' => '0','languages' => NULL,'currency_code' => NULL,'status' => 'Active','featured' => 'Yes','is_header' => 'Yes','type' => 'merchant','created_at' => '2017-09-15 11:13:05','updated_at' => '2020-02-04 14:55:52','deleted_at' => NULL),
  array('id' => '10003','full_name' => 'mick','user_name' => 'Hans','email' => 'mick@gmail.com','password' => '$2y$10$NXDuZNrawRwGboIkg/GcsuxqqrWQpnF6HotgVTIv7CxefYVeDPRNa','remember_token' => 'VF7iyaKnFcqFaYXd48Rh0DIoNrovuqVk0cFuNqw1Msh6GDvxlSIBwIXjbumi','store_name' => 'Dea stylish women\'s wear shop','already_selling' => NULL,'product_categories' => NULL,'dob' => NULL,'gender' => NULL,'location' => NULL,'bio' => NULL,'website' => NULL,'google_id' => NULL,'twitter_id' => NULL,'facebook_id' => NULL,'device_type' => NULL,'device_id' => NULL,'timezone' => 'UTC','timeformat' => '0','languages' => NULL,'currency_code' => NULL,'status' => 'Active','featured' => 'Yes','is_header' => 'Yes','type' => 'merchant','created_at' => '2017-09-19 20:24:12','updated_at' => '2020-01-31 20:36:15','deleted_at' => NULL),
  array('id' => '10004','full_name' => 'John','user_name' => 'Ivan','email' => 'john@gmail.com','password' => '$2y$10$7NUh.r3i5hujgaBkIbes/ercvsUDVU/mmTh9NyWBSbUbMnf8vhpju','remember_token' => 'XGwadzAMnZDBcsShxsFSRviLx5C2d2cFi6MVfyebKnfqgJvbYMGCRcESOdXo','store_name' => 'John','already_selling' => NULL,'product_categories' => NULL,'dob' => '1979-02-16','gender' => 'Male','location' => '','bio' => '','website' => '','google_id' => NULL,'twitter_id' => NULL,'facebook_id' => NULL,'device_type' => NULL,'device_id' => NULL,'timezone' => 'UTC','timeformat' => '0','languages' => NULL,'currency_code' => NULL,'status' => 'Active','featured' => 'Yes','is_header' => 'Yes','type' => 'buyer','created_at' => '2017-09-19 20:58:53','updated_at' => '2020-02-05 11:50:35','deleted_at' => NULL),
  array('id' => '10005','full_name' => 'Uivan','user_name' => 'Uivan','email' => 'uivan@gmail.com','password' => '$2y$10$YlKD6QXF3yVVCqfwwcPA6.FBbb0iYcY5IC7uFaz8ZoPBqdyAaHWqa','remember_token' => 'C9yUB5wtjA6zG0GXM6yCxgTQYX6esOgHigIgVp730vg58BlYZ2z1E3ffaKpY','store_name' => 'John','already_selling' => NULL,'product_categories' => NULL,'dob' => NULL,'gender' => NULL,'location' => NULL,'bio' => NULL,'website' => NULL,'google_id' => NULL,'twitter_id' => NULL,'facebook_id' => NULL,'device_type' => NULL,'device_id' => NULL,'timezone' => 'UTC','timeformat' => '0','languages' => NULL,'currency_code' => NULL,'status' => 'Active','featured' => 'Yes','is_header' => 'Yes','type' => 'buyer','created_at' => '2017-09-19 20:58:53','updated_at' => '2017-09-21 22:54:26','deleted_at' => NULL),
  array('id' => '10007','full_name' => 'Thomas','user_name' => 'Harry','email' => 'trioanglespiffy@gmail.com','password' => '$2y$10$7AYWwgN6CW1SFOgW95ZTL.n0zSDZSHLdcu1yNXJF13cnqjXY7d5rS','remember_token' => 'xvsEBqY6zwfzdsZdG6QjWQjTUkNW5tyzV3mvnLPdNCW1FYoBWab9Xc7W6gdG','store_name' => 'Cristina Jewelry shop','already_selling' => NULL,'product_categories' => NULL,'dob' => '1992-01-28','gender' => 'Male','location' => '','bio' => '','website' => '','google_id' => NULL,'twitter_id' => NULL,'facebook_id' => NULL,'device_type' => NULL,'device_id' => NULL,'timezone' => 'UTC','timeformat' => '0','languages' => NULL,'currency_code' => NULL,'status' => 'Active','featured' => 'No','is_header' => 'No','type' => 'merchant','created_at' => '2020-02-04 10:53:38','updated_at' => '2020-02-04 11:16:40','deleted_at' => NULL),
  array('id' => '10008','full_name' => 'William ','user_name' => 'James','email' => 'Jamestrio@gmail.com','password' => '$2y$10$WTtt2.kmoG7gRGYk3pKZpe8thIPG//YG5f1qP.I0EPbgtt5HmrIMa','remember_token' => 'otndUeX0kkJjjnjmRksnFq25TERfewFbm70cHm8rlG3PMdtXPGAH5xwamSLg','store_name' => 'Modern Art store ','already_selling' => NULL,'product_categories' => NULL,'dob' => NULL,'gender' => NULL,'location' => NULL,'bio' => NULL,'website' => NULL,'google_id' => NULL,'twitter_id' => NULL,'facebook_id' => NULL,'device_type' => NULL,'device_id' => NULL,'timezone' => 'UTC','timeformat' => '0','languages' => NULL,'currency_code' => NULL,'status' => 'Active','featured' => 'No','is_header' => 'No','type' => 'merchant','created_at' => '2020-02-04 11:21:02','updated_at' => '2020-02-04 11:46:46','deleted_at' => NULL)
));
	}
}
